import type { SupportedDocumentState } from '@/config/supportedDocumentStates';

/** Honest V1 framing — required on every generated draft document. */
export function buildAttorneyDisclaimer(state: SupportedDocumentState, docType: 'lease' | 'purchase'): string {
  const docLabel =
    docType === 'lease'
      ? 'Closewell Residential Lease Agreement (Draft)'
      : 'Closewell Residential Purchase Agreement (Draft)';

  return (
    `IMPORTANT NOTICE — NOT ATTORNEY-REVIEWED. This document is a ${docLabel} for ${state}. ` +
    `It was generated by Closewell based on information you provided and a general understanding of ${state} law. ` +
    `It has not been reviewed by a licensed attorney. It is not an official state association form and is not a substitute ` +
    `for counsel-approved or association-promulgated contracts. Consult a real estate attorney licensed in ${state} ` +
    `before relying on this document for a real transaction.`
  );
}
